export const languageList = {
  arabic: "ar",
  assamese: "as",
  bengali: "bn",
  "bihari languages": "bh",
  tibetan: "bo",
  chinese: "zh",
  german: "de",
  maldivian: "dv",
  dutch: "nl",
  greek: "el",
  english: "en",
  french: "fr",
  hindi: "hi",
  indonesian: "id",
  italian: "it",
  japanese: "ja",
  kannada: "kn",
  kashmiri: "ks",
  korean: "ko",
  latin: "la",
  malayalam: "ml",
  marathi: "mr",
  nepali: "ne",
  oriya: "or",
  punjabi: "pa",
  russian: "ru",
  sanskrit: "sa",
  sindhi: "sd",
  spanish: "es",
  tamil: "ta",
  telugu: "te",
  thai: "th",
  turkish: "tr",
  urdu: "ur",
};
